syntax on
set encoding=utf-8
set shiftwidth=4
set textwidth=80
set laststatus=2
set smartindent
set errorbells
set autoindent
set tabstop=4
set expandtab
set showmatch
set autochdir
set incsearch
set hlsearch
set mouse+=a
set confirm
set ff=unix
set number
set paste